language: c

compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install xorg
    - sudo apt-get install libwayland0
    - sudo apt-get install libosmesa6
    - sudo apt-get install xcb
    - sudo apt-get install pkg-config
    - wget https://launchpad.net/ubuntu/+archive/primary/+files/xcb-proto_1.11.orig.tar.gz
    - tar -xpzf xcb-proto_1.11.orig.tar.gz
    - cd xcb-proto-1.11
    - ./configure
    - make
    - sudo make install
    - cd ..
    - wget http://xcb.freedesktop.org/dist/libxcb-1.11.tar.gz
    - tar -xpzf libxcb-1.11.tar.gz
    - cd libxcb-1.11
    - ./configure
    - make
    - sudo make install
    - cd ..
    - sudo apt-get install libgles2-mesa-dev
    - sudo apt-get install libgbm-dev
    - sudo ldconfig

# Note, add > /dev/null to the end of all these commands once they work
install:
    - git clone git://github.com/cloudef/wlc.git
    - cd wlc
    - git submodule update --init --recursive
    - cmake . -DCMAKE_INSTALL_PREFIX=/usr
    - make
    - sudo make install
    - sudo ldconfig
    - cd ..

script:
    cmake .
    make

notifications:
    email: false
