language: c

compiler:
    - gcc
    - clang

# Note, eventually add > /dev/null to the end of all these commands once they work
before_install:
    - sudo apt-get update -qq
    # Install xorg, wayland, mesa, and xcb for wlc
    - sudo apt-get install xorg
    - sudo apt-get install libwayland0
    - sudo apt-get install libosmesa6
    - sudo apt-get install xcb
    # Install pkg-config for xcb-proto
    - sudo apt-get install pkg-config
    # Install xcb-proto for wlc
    - wget https://launchpad.net/ubuntu/+archive/primary/+files/xcb-proto_1.11.orig.tar.gz
    - tar -xpzf xcb-proto_1.11.orig.tar.gz
    - cd xcb-proto-1.11
    - ./configure
    - make
    - sudo make install
    - cd ..
    # Install libxcb for wlc
    - wget http://xcb.freedesktop.org/dist/libxcb-1.11.tar.gz
    - tar -xpzf libxcb-1.11.tar.gz
    - cd libxcb-1.11
    - ./configure
    - make
    - sudo make install
    - cd ..
    # Install yacc for libxkbcommon
    - sudo apt-get install bison
    # Install libxkbcommon for wlc
    - wget http://xkbcommon.org/download/libxkbcommon-0.5.0.tar.xz
    - tar -xf libxkbcommon-0.5.0.tar.xz
    - cd libxkbcommon-0.5.0
    - ./configure
    - make
    - sudo make install
    - cd ..
    # Install libtool for libinput and mtdev
    - sudo apt-get install libtool
    # Install mtdev for libinput
    - wget http://bitmath.org/code/mtdev/mtdev-1.1.5.tar.gz
    - tar -xpzf mtdev-1.1.5.tar.gz
    - cd mtdev-1.1.5 
    - ./configure
    - make
    - sudo make install
    - cd ..
    # Install libevdev for libinput
    - git clone git://anongit.freedesktop.org/libevdev
    - cd libevdev
    - ./autogen.sh --prefix=/usr/ --disable-static
    - make
    - sudo make install
    - cd ..
    # Install libudev for libinput
    - sudo apt-get install libudev0
    - sudo apt-get install libudev-dev
    # Install libinput for wlc
    - git clone git://anongit.freedesktop.org/wayland/libinput
    - cd libinput
    - ./autogen.sh --prefix=/usr/
    - make
    - sudo make install
    - cd ..
    # Install mesa libs for wlc
    - sudo apt-get install libgles2-mesa-dev
    - sudo apt-get install libgbm-dev
    # Update shared object libs
    - sudo ldconfig

install:
    # Install wlc for sway
    - git clone git://github.com/cloudef/wlc.git
    - cd wlc
    - git submodule update --init --recursive
    - cmake . -DCMAKE_INSTALL_PREFIX=/usr
    - make
    - sudo make install
    - cd ..
    # Update shared object libs
    - sudo ldconfig

script:
    # Install sway
    cmake .
    make

notifications:
    email: false
