language: c

compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install xorg
    - sudo apt-get install libwayland0
    - sudo apt-get install libglapi-mesa
    - sudo apt-get install libosmesa6
    - sudo ldconfig

# Note, add > /dev/null to the end of all these commands once they work
install:
    - git clone git://github.com/cloudef/wlc.git
    - cd wlc
    - cmake . -DCMAKE_INSTALL_PREFIX=/usr
    - make
    - sudo make install
    - cd ..

script:
    cmake .
    make

notifications:
    email: false
